export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION';
export const ADD_SUBSCRIPTION_SUCCESS = 'ADD_SUBSCRIPTION_SUCCESS';
export const ADD_SUBSCRIPTION_ERROR = 'ADD_SUBSCRIPTION_ERROR';

export const DELETE_SUBSCRIPTION = 'DELETE_SUBSCRIPTION';
export const DELETE_SUBSCRIPTION_SUCCESS = 'DELETE_SUBSCRIPTION_SUCCESS';
export const DELETE_SUBSCRIPTION_ERROR = 'DELETE_SUBSCRIPTION_ERROR';

export const UPDATE_SUBSCRIPTION = 'UPDATE_SUBSCRIPTION';
export const UPDATE_SUBSCRIPTION_SUCCESS = 'UPDATE_SUBSCRIPTION_SUCCESS';
export const UPDATE_SUBSCRIPTION_ERROR = 'UPDATE_SUBSCRIPTION_ERROR';

export const FETCHING_SUBSCRIPTIONS = 'FETCHING_SUBSCRIPTIONS';
export const FETCHING_SUBSCRIPTIONS_SUCCESS = 'FETCHING_SUBSCRIPTIONS_SUCCESS';
export const FETCHING_SUBSCRIPTIONS_ERROR = 'FETCHING_SUBSCRIPTIONS_ERROR';

export const SEARCH_SUBSCRIPTION = 'SEARCH_SUBSCRIPTION';
export const SEARCH_SUBSCRIPTIONS_SUCCESS = 'SEARCH_SUBSCRIPTIONS_SUCCESS';
export const SEARCH_SUBSCRIPTIONS_ERROR = 'SEARCH_SUBSCRIPTIONS_ERROR';

export const FETCHING_ID_MEMBERS = 'FETCHING_ID_MEMBERS';
export const FETCHING_ID_MEMBERS_SUCCESS = 'FETCHING_ID_MEMBERS_SUCCESS';
export const FETCHING_ID_MEMBERS_ERROR = 'FETCHING_ID_MEMBERS_ERROR';