export const ADD_BOOK_RESERVATION = 'ADD_BOOK_RESERVATION';
export const ADD_BOOK_RESERVATION_SUCCESS = 'ADD_BOOK_RESERVATION_SUCCESS';
export const ADD_BOOK_RESERVATION_ERROR = 'ADD_BOOK_RESERVATION_ERROR';

export const DELETE_BOOK_RESERVATION = 'DELETE_BOOK_RESERVATION';
export const DELETE_BOOK_RESERVATION_SUCCESS = 'DELETE_BOOK_RESERVATION_SUCCESS';
export const DELETE_BOOK_RESERVATION_ERROR = 'DELETE_BOOK_RESERVATION_ERROR';

export const UPDATE_BOOK_RESERVATION = 'UPDATE_BOOK_RESERVATION';
export const UPDATE_BOOK_RESERVATION_SUCCESS = 'UPDATE_BOOK_RESERVATION_SUCCESS';
export const UPDATE_BOOK_RESERVATION_ERROR = 'UPDATE_BOOK_RESERVATION_ERROR';

export const FETCHING_BOOK_RESERVATIONS = 'FETCHING_BOOK_RESERVATIONS';
export const FETCHING_BOOK_RESERVATIONS_SUCCESS = 'FETCHING_BOOK_RESERVATIONS_SUCCESS';
export const FETCHING_BOOK_RESERVATIONS_ERROR = 'FETCHING_BOOK_RESERVATIONS_ERROR';

export const SEARCH_BOOK_RESERVATION = 'SEARCH_BOOK_RESERVATION';
export const SEARCH_BOOK_RESERVATIONS_SUCCESS = 'SEARCH_BOOK_RESERVATIONS_SUCCESS';
export const SEARCH_BOOK_RESERVATIONS_ERROR = 'SEARCH_BOOK_RESERVATIONS_ERROR';