export const ADD_MEMBER = 'ADD_MEMBER';
export const ADD_MEMBER_SUCCESS = 'ADD_MEMBER_SUCCESS';
export const ADD_MEMBER_ERROR = 'ADD_MEMBER_ERROR';

export const DELETE_MEMBER = 'DELETE_MEMBER';
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS';
export const DELETE_MEMBER_ERROR = 'DELETE_MEMBER_ERROR';

export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const UPDATE_MEMBER_SUCCESS = 'UPDATE_MEMBER_SUCCESS';
export const UPDATE_MEMBER_ERROR = 'UPDATE_MEMBER_ERROR';

export const FETCHING_MEMBERS = 'FETCH_MEMBERS';
export const FETCHING_MEMBERS_SUCCESS = 'FETCHING_MEMBERS_SUCCESS';
export const FETCHING_MEMBERS_ERROR = 'FETCHING_MEMBERS_ERROR';

export const SEARCH_MEMBER = 'SEARCH_MEMBER';
export const SEARCH_MEMBERS_SUCCESS = 'SEARCH_MEMBERS_SUCCESS';
export const SEARCH_MEMBERS_ERROR = 'SEARCH_MEMBERS_ERROR';